# Site/SEO settings
email: annegaranse@gmail.com
baseurl: "https://garanse.github.io"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Garanse
title: Galerie
description: >
  Galerie de Garanse.
url:
# twitter_username: thomasvaeth
# default_img: /assets/images/seo.jpg
social:
  - name: instagram
    url: https://www.instagram.com/annegaranse
  - name : facebook
    url: https://www.facebook.com/profile.php?id=100013402509434
  # - name: linkedin
    # url: https://www.linkedin.com/in/thomasvaeth/
  # - name: github
    # url: https://github.com/samesies
  # - name: codepen
    # url: https://codepen.io/thomasvaeth/

# Contact settings
# contact_img: assets/images/placeholder-28.jpg
# formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
# disqus: test-apkdzgmqhj

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Garanse
    bio: Blabla
    url: http://garanse.github.io

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Image size
image-size:
  - 240
  - 360
  - 480
  - 720
  - 1080

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
  # - style-guide.html
